version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm i
      - run: npm run build
      - run:
          name: deploy
          command: |
            cp now.json dist/
            cd dist
            ../node_modules/.bin/now -t ${NOW_TOKEN} alias rm vlingo-schemata-ui.now.sh --yes
            ../node_modules/.bin/now -t ${NOW_TOKEN} -C --public
            ../node_modules/.bin/now -t ${NOW_TOKEN} alias

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
